// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://kfjttnxidwmkgvcshwrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmanR0bnhpZHdta2d2Y3Nod3JmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3NzU3NTIsImV4cCI6MjA3ODM1MTc1Mn0.DLJE6WYzbeWgvNlIco2O-eQiBcAgeU_6X6ZjUbURVrE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);